### ISSUE TITLE
Using custom configs and modules located outside the tracklab and sn-gamestate directories

### ISSUE THREAD

**Issue by Tengoles** [TrackingLaboratory/tracklab#5]
Hello! been trying to learn how to use tracklab on the past days, so far managed to add my own object detection module. To do that I needed to add a custom config yaml to `sn_gamestate/configs/custom_config.yaml`, a module config yaml to `tracklab/configs/modules/bbox_detector/fake_yolov8.yaml` and finally the actual module to `tracklab/wrappers/detect_multiple/fake_yolov8.py`. This is currently working as desired by running `tracklab -cn custom_config` 

The issue is that all those files had to be added to the cloned `sn-gamestate` and `tracklab` directories. What would I have to change if I wanted to have those configs on a custom directory outside of `tracklab` and `sn_gamestate`?

**Comment by victorjoos** [comment]
Hi Tengoles,

You're almost there! The first step would be to move everything to sn_gamestate : `tracklab/configs/modules/bbox_detector/fake_yolov8.yaml` can go in `sn_gamestate/configs/modules/bbox_detector/fake_yolov8.yaml` and `tracklab/wrappers/detect_multiple/fake_yolov8.py` can be moved anywhere in the `sn_gamestate` package (for example in `sn_gamestate/bbox_detector/fake_yolov8.py`). You'll have to change the `_target_` value inside the fake_yolov8.yaml.

Once you've done this, the simplest way to create your own repo is to copy some files from sn_gamestate and change the name of the directories and inside some files : you'll need at least `pyproject.toml`, the config directory and  `sn_gamestate/config_finder.py`. You only need to keep the new configs, all of the old ones will be merged from tracklab or sn_gamestate. If you go this way, don't forget to `poetry install` or `pip install -e .` your new repo, because that's how tracklab finds the new config directory.

Don't hesitate to get back to us if you don't get this to work.

**Comment by victorjoos** [comment]
I would suggest moving configs and bbox_detector in their own common package, if I use "gsr" as example name, it would look like this :
```
GameStateChallenge/
    data/
    src/
        tracklab/
        sn-gamestate/
        gsr/
            configs/
                modules/
                    bbox_detection/
                        fake_yolov8.yaml
                __init__.py
                custom_config.yaml            
            bbox_detector/
                fake_yolov8.py
            config_finder.py
    README.md
    pyproject.toml
```

Then, the content of pyproject.toml could look more or less like this : 

```toml
[tool.poetry]
name = "gsr-challenge"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = [{include = "gsr", from = "src"}] # IMPORTANT : this enables including the gsr package

[tool.poetry.dependencies]
python = "^3.9"
# Any additional dependencies here

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins.tracklab_plugin]
gsr_challenge = "gsr.config_finder:ConfigFinder" # IMPORTANT : this is the "magic" that enables tracklab to find the configs
```

`config_finder.py` would then look like this : 

```python
class ConfigFinder:
    config_package = "pkg://gsr.configs"
```

The name of the class is not important, but the `config_package` name is important. It can either be like here, with the "pkg://" prefix, and then [Hydra](https://hydra.cc/) will search for the configurations using python's packages functionality, or it can be a path, relative to where the code is run, but this is much more error-prone.

When you're defining fake_yolo.yaml, you would change the `_target_: gsr.bbox_detector.fake_yolov8.FakeYolov8`
